name: continuous intergration

on:
  push:
    branches: [feat/*]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, window-latest]
        node-version: [14.x, 16.x]

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm install

      - name: lint
        run: npm run lint

      - name: build
        run: npm run build
